### ISSUE TITLE
Limit for auto-upgrades?

### ISSUE THREAD

**Issue by jgillman** [DomT4/homebrew-autoupdate#1]
I really like how this works, but I wish I could have it only do `brew update` without `brew upgrade`.

Personally, I'm a little leery about automatically upgrading *everything* I've installed because I know that something will eventually break and it will take forever to hunt down which thing upgraded...

Thoughts?

**Comment by DomT4** [comment]
I was thinking about this the other night actually, and I agree `brew update` is a more normal/useful course of action for most users.

`brew upgrade` is relatively fine for me, because if it silently breaks something I can dig through Homebrew's commits to find out what it was, and then quickly push a fix for that breakage, but that experience is less than optimal for people who don't actively watch Homebrew so closely.

Will look into making the upgrade element an option add-on to the command here ASAP.

**Comment by jgillman** [comment]
Great! Appreciate the quick response.

Another related though, though this is probably more of a v2 kind of thing: If you wanted to go deep users could maintain a whitelist/blacklist of stuff that's okay to auto-upgrade. Personally most of my stuff is fine if it auto-upgrades, but a few things like `vips` I need to keep an eye on what actually upgrades.

**Comment by DomT4** [comment]
https://github.com/DomT4/homebrew-autoupdate/commit/2ba69c31e98d0c90b40c6c38d4dfaa27c25745dd has landed :)

**Comment by jgillman** [comment]
:+1: Awesome! Thank you :)
