### ISSUE TITLE
Question on notifications…

### ISSUE THREAD

**Issue by jprokos** [DomT4/homebrew-autoupdate#18]
Will autoupdate and notifications only work if the current user is admin? I generally only switch to my admin account to update software and then I sign out. Or I  _su admin_ in terminal to work on brew from my user account. I am not seeing any notifications from homebrew-autoupdate.

Is there a way to manually set the time this autoupdate happens in the plist?

**Comment by DomT4** [comment]
Apologies for the delay here; I subscribe to far too much on GitHub and end up having to wade through thousands of notifications to find my own stuff.

The autoupdate here, being triggered by a user-specific `launchctl` job (because the `.plist` resides in `~/Library/LaunchAgents` rather than `/Library/LaunchAgents`), essentially does require the user running it to be the same user _(or one with a higher privilege level)_ as the one that has control over the directories Homebrew resides in.

> Is there a way to manually set the time this autoupdate happens in the plist?

Currently it's every 24 hours. It'd probably be fairly simple to tweak the tool to make that a little more user flexible; I'll look into it.
